### ISSUE TITLE
what font does waybar use?

### ISSUE THREAD

**Issue by SkelyTony** [ketsumashu/dots#1]
![image](https://user-images.githubusercontent.com/78977752/154819051-bb9da391-76e0-4a61-a5db-d1047a724518.png)

**Comment by ketsumashu** [comment]
meslo nerdfont for powerlevel10k
https://aur.archlinux.org/packages/ttf-meslo-nerd-font-powerlevel10k

**Comment by SkelyTony** [comment]
it seems not to work : ( 
https://search.nixos.org/packages?channel=21.11&show=meslo-lgs-nf&from=0&size=50&sort=relevance&type=packages&query=powerlevel10k

**Comment by ketsumashu** [comment]
I'm not familiar with NixOS, but maybe https://nixos.wiki/wiki/Fonts , "Installing specific fonts from nerdfonts" section solves the problem?

**Comment by SkelyTony** [comment]
hello, it was an nixos related issue and now it got fixed, thank you
